### ISSUE TITLE
Улучшение Travis CI

### ISSUE THREAD

**Issue by denisstasyev** [denisstasyev/Information_Security_JS#25]
Auto raise version on merge into master and generate Changelog

**Comment by mikhan333** [comment]
And auto provide new "Realise" with pull request in master

**Comment by denisstasyev** [comment]
Думаю не надо автоматизировать, так как всё-равно придётся заходить и смотреть вручную версию в package.json при релизе. Имеет смысл только вместе с автоматизацией релиза делать, однако как это реализовать я не знаю
