### ISSUE TITLE
Разработка шифра AES

### ISSUE THREAD

**Issue by mikhan333** [denisstasyev/Information_Security_JS#30]
Версии:
- [x] ECB
- [x] CBC 
- [x] ~~GCM (нет в библиотеке) (возможно https://www.npmjs.com/package/node-aes-gcm)~~

Дополнительно:
- [x] CTR
- [x] CFB
- [x] OFB

**Comment by denisstasyev** [comment]
Сделана форма для Шифрования, необходимо написать сами методы

**Comment by mikhan333** [comment]
Следующие шаги:
1. Доделать форму для расшифрования (включая json)
2. Сделать шифрование для ECB

**Comment by denisstasyev** [comment]
Доделываю форму для расшифрования (включая json) и расшифрование aes

**Comment by mikhan333** [comment]
Следующие шаги:
1. Возможность ввода iv в encrypt форме, либо вызов автоматического генератора для iv (который необходимо написать). Выбор должен появляется только для версий, где он требуется
2. Возможность ввода iv в decrypt форме (и в json). Выбор должен появляется только для версий, где он требуется
3. Дописать все версии aes

**Comment by denisstasyev** [comment]
Делаю CBC

**Comment by denisstasyev** [comment]
В выводе при шифровании iv будет выводиться, при расшифровании будет использоваться константа из кода

**Comment by denisstasyev** [comment]
CBC с константным iv сделан

**Comment by mikhan333** [comment]
Под константным имелось ввиду: функция, которая возвращает константный. А сейчас даже в decrypt захардкодено) gl hf

**Comment by denisstasyev** [comment]
> Под константным имелось ввиду: функция, которая возвращает константный. А сейчас даже в decrypt захардкодено) gl hf

Начинаю норм делать

**Comment by denisstasyev** [comment]
Добавлена возможность выставления произвольных iv

**Comment by denisstasyev** [comment]
Начинаю CTR

**Comment by denisstasyev** [comment]
Готов CTR, делаю CFB

**Comment by denisstasyev** [comment]
Готов AES-256/CFB, начинаю OFB

**Comment by denisstasyev** [comment]
Готов OFB

**Comment by mikhan333** [comment]
Осталось: исправление ввода iv и всё связанное. Делаю я

**Comment by denisstasyev** [comment]
> Осталось: исправление ввода iv и всё связанное. Делаю я

Ок, но я думаю сейчас верная логика с ошибкой в iv
