### ISSUE TITLE
RSA

### ISSUE THREAD

**Issue by denisstasyev** [denisstasyev/Information_Security_JS#49]
https://www.npmjs.com/package/node-rsa

**Comment by GRISHNOV** [comment]
Hi! I have prepared an RSA interface for you to sync with the backend. You can find it [here](https://github.com/GRISHNOV/Information_Security_Web_Service/tree/rsa_typescript_interface)

**Comment by mikhan333** [comment]
@GRISHNOV Зачем?) лучше бы gost сделал бы:)

**Comment by mikhan333** [comment]
close #50

**Comment by denisstasyev** [comment]
Реализовано в версии 2.1
